services:
  sharelatex:
    restart: always
    image: ghcr.io/takenagain/overleaf:staging
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    # Uncomment if you wish to expose this directly to the public internet without a reverse proxy for whatever reason
    #ports:
    #  - 80:80
    stop_grace_period: 60s
    volumes:
      # Host data root defaults to ${HOME}/sharelatex and can be changed with SHARELATEX_DATA_ROOT_DIR.
      - ${HOME}/${SHARELATEX_DATA_ROOT_DIR:-sharelatex}/sharelatex_data:/var/lib/overleaf
      ########################################################################
      ####  Server Pro: Uncomment the following line to mount the docker  ####
      ####             socket, required for Sibling Containers to work    ####
      ########################################################################
      # - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env

  mongo:
    restart: always
    image: mongo:8.0
    container_name: mongo
    command: "--replSet overleaf"
    volumes:
      - ${HOME}/${SHARELATEX_DATA_ROOT_DIR:-sharelatex}/mongo_data:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      # Required when using the automatic database setup for initializing the replica set.
      # This override is not needed when running the setup after starting up mongo.
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:trixie
    container_name: redis
    volumes:
      - ${HOME}/${SHARELATEX_DATA_ROOT_DIR:-sharelatex}/redis_data:/data

  # ldap:
  #    restart: always
  #    image: rroemhild/test-openldap
  #    container_name: ldap

  # See https://github.com/jwilder/nginx-proxy for documentation on how to configure the nginx-proxy container,
  # and https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx for an example of some recommended
  # settings. We recommend using a properly managed nginx instance outside of the Overleaf Server Pro setup,
  # but the example here can be used if you'd prefer to run everything with docker-compose

  # nginx-proxy:
  #     image: jwilder/nginx-proxy
  #     container_name: nginx-proxy
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     volumes:
  #       - /var/run/docker.sock:/tmp/docker.sock:ro
  #       - /home/overleaf/tmp:/etc/nginx/certs

networks:
  default:
    name: overleaf
